name: nezha-socat-docker-build
on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#    paths:
#      - 'nezha-socat/**'
env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository_owner }}/nezha-socat
  ALT_IMAGE_NAME: ${{ github.repository_owner }}/nezha
  #TAG: latest
  ALT_TAG: socat
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          cd nezha-socat
          docker build -t ${{ env.REGISTRY }}/${{ env.ALT_IMAGE_NAME }}:${{ env.ALT_TAG }} .
          docker push ${{ env.REGISTRY }}/${{ env.ALT_IMAGE_NAME }}:${{ env.ALT_TAG }}
          # 构建第一个镜像
          #docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
          #docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          # 构建第二个镜像（实际上是同一个镜像，只是打了不同的标签）
          #docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.REGISTRY }}/${{ env.ALT_IMAGE_NAME }}:${{ env.ALT_TAG }}
          #docker push ${{ env.REGISTRY }}/${{ env.ALT_IMAGE_NAME }}:${{ env.ALT_TAG }}
      - name: Clean
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
